CREATE TABLE refresh_tokens (
	id UUID PRIMARY KEY DEFAULT uuidv7(),
	token VARCHAR(500) NOT NULL UNIQUE,
	user_id UUID NOT NULL REFERENCES users(id),
	expires_at TIMESTAMPTZ NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)
