server:
  port: 8080

spring:
  application:
    name: backend

  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/legend_booking
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl_auto: validate

  flyway:
    enabled: true
